language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install .[test]

script:
  - py.test -v --cov nipype --cov-config .coveragerc --cov-report xml:cov.xml -c PyBASC/pytest.ini --doctest-modules PyBASC -n auto

after_script:
  - codecov --file cov.xml --flags unittests -e TRAVIS_JOB_NUMBER