language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install .[test]

script:
  - py.test -vs -n auto --cov matchgroup --cov-config .coveragerc --cov-report xml:cov.xml PyBASC

after_script:
  - codecov --file cov.xml --flags unittests -e TRAVIS_JOB_NUMBER